### ISSUE TITLE
Compare against other tmp libs on metabench

### ISSUE THREAD

**Issue by erikzenker** [deepgrace/monster#2]
Hi,

Do you know about metaben.ch and do you consider to compare compile time Performance against other libs listed there?

**Comment by deepgrace** [comment]
No. 
It's obviously that Monster is running faster in most cases as it's pure type programming, not like the way Boost.Hana does, which is value based.

**Comment by erikzenker** [comment]
Metaben.ch does also compare pure type based libs e.g.: brigand, meta, mp11 kvasir, tmp, metal. Would be interesting to compare against those.
